name: aplicativo_furia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  dash_chat_custom: ^0.0.29
  chat_gpt_sdk: ^3.1.5
  path_provider: ^2.0.11
  http: ^1.3.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  provider: ^6.1.5
  go_router: ^15.1.1
  youtube_player_flutter: ^9.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/pdfs/Furia_Esports.pdf
    - assets/images/furia_logo.png
    - assets/images/mibr_logo.jpeg
    - assets/images/ence_logo2.png

